### DISCUSSION TITLE
Actors

### DISCUSSION THREAD

**Discussion by jochumdev** [go-orb/go-orb#12] [Ideas]
[@g41797](https://github.com/g41797) brought up the idea of adding 'Actors' to go-orb.

Actors in dapr are described here: https://docs.dapr.io/developing-applications/building-blocks/actors/actors-overview/
and here https://www.microsoft.com/en-us/research/project/orleans-virtual-actors/ - the Overview is very informative.

**Comment by jochumdev** [comment]
# runner

## Intro

In the concept below I outline a yaml configuration where I show the most features I would love to have in a **runner**.
A runner could be a Service that run's these. 

The runner would be custom compiled with some easy instructions so it can serve for example "shared.proto.userpb.v1".

## The Dream

```yaml
runner:
  name: "user_register"
  version: v0.0.1

  arg: shared.proto.userpb.v1.UserReq
  result: shared.proto.userpb.v1.UserResponse

  hooks:
    - name: checked
      arg: shared.proto.userpb.v1.User
    - name: notified
      arg: shared.proto.userpb.v1.User
    - name: verified
      arg: shared.proto.userpb.v1.User
    - name: failed
      arg: shared.proto.userpb.v1.User
    - name: registered
      arg: shared.proto.userpb.v1.User

  # run is the pipeline to call
  run:
    - description: Verify the User
      action: orb_call
      service: user.svc.orb.org
      endpoint: User.Verify
      success:
        - description: Send verfication mail
          action: orb_call
          service: mail.svc.orb.org
          endpoint: MailUser.Verify
          # Means keep the previous result
          pipe: false

       - description: Wait for answer
          action: orb_poll_call
          service: user.svc.orb.org
          endpoint: User.Verified
    
    - hook: checked

    - action: orb_call
      # orb_call or better go-orb/client can find an endpoint without knowing the service.
      # service: db.svc.orb.org
      endpoint: DBUser.Store
      success:             
        - action: orb_call
          service: mail.svc.orb.org
          endpoint: MailUser.Notify

     - description: Do something in parallel
       action: orb_parallel
       run:
         - action: orb_call
         - action: orb_call
  sucess:
    - hook: registered
  error:
    - hook: failed
    - action: orb_return_err
```
