### ISSUE TITLE
Server config

### ISSUE THREAD

**Issue by jochumdev** [go-orb/go-orb#16]
The current config format of `server` isn't conform with other orb plugins, we have to change that:

**old**:
```yaml
service1:
  server:
    http:
      gzip: true
      handlers:
        - echo
        - auth
      entrypoints:
        - name: ep1
          address: :4512
          insecure: true
          h2c: true
    grpc:
      handlers:
        - echo
        - auth
      insecure: true
      entrypoints:
        - name: ep2
          address: :4513 
```

**new**:
```yaml
service1:
  server:
    middlewares:
      - plugin: log
        level: trace
      - plugin: opentelemetry
        server: grpc://otel-collector:4317
    handlers:
      - echo
      - auth
    entrypoints:
      - plugin: grpc
        insecure: true
        reflection: false
        middlewares:
         # This middlewares are for this entrypoint only.
          - plugin: recover
        handlers:
         # Same as with this handlers.
          - grpc-only-handler
      - plugin: http
        insecure: true

```
