### ISSUE TITLE
chore(server): Remove per entrypoint handlers and middlewares

### ISSUE THREAD

**Issue by jochumdev** [go-orb/go-orb#23]
While it was a nice idea to make handlers and middlewares available per entrypoint I found that it's as mess to configure them with Wire.

This will remove support for that to make it clearer howto configure server.

**Comment by jochumdev** [comment]
Also change back config:

```yaml
service1:
  server:
    logging:
        plugin: lumberjack
        level: INFO
    handlers:
      - UserInfo
    middlewares:
      - middleware-1
      - middleware-2
    entrypoints:
      - name: hertzhttp
        plugin: hertz
        http2: false
        insecure: true

      - name: grpc
        plugin: grpc
        insecure: true
        reflection: false

      - name: http
        plugin: http
        insecure: true

      - name: drpc
        plugin: drpc
```

New:

```yaml
service1:
  server:
    logging:
        plugin: lumberjack
        level: INFO
    handlers:
      - UserInfo
    middlewares:
      - middleware-1
      - middleware-2
    entrypoints:
      hertzhttp:
        plugin: hertz
        http2: false
        insecure: true

      grpc:
        plugin: grpc
        insecure: true
        reflection: false

      http:
        plugin: http
        insecure: true

      orb-drpc:
        plugin: drpc
```
