### ISSUE TITLE
feat(config): Add globals

### ISSUE THREAD

**Issue by jochumdev** [go-orb/go-orb#28]
I want this to be possible.

```yaml
# Globals are applied to each service, individual services can overwrite them.
globals:
  client:
    preferredTransports: 
      - orb-drpc # orb uses it's own wire Format for results on top of DRPC to deliver responses for metadata.
      - grpc
  server:
    drpc:
      # Templating happens at the service level.
      listen: unix://{{env.XDG_RUNTIME_DIR}}/{{project.Name}}/{{project.ID}}/{{service.App.Name}}-drpc.sock
    grpc:
      listen: unix://{{env.XDG_RUNTIME_DIR}}/{{project.Name}}/{{project.ID}}/{{service.App.Name}}-grpc.sock
  kvstore:
    # kvstore/natsjs is fully compatible with these settings 
    # to go-micro/store/natsjs which is used in opencloud.
    plugin: natsjs
    servers:
      - nats://localhost:9233
    bucketPerTable: false
    jsonKeyValues: true
    compress: false
  registry:
    # registry/micro-kvstore is a opencloud/nats-js-kv compatible registry.
    plugin: micro-kvstore
    defaultTransport: grpc
    kvstore:
      plugin: natsjs
      bucketPerTable: false
      jsonKeyValues: true
      compress: false
      servers:
        - nats://localhost:9233

services:
   nats:
     port:  9233
```

Config should have an option enable/disable globals.
