### ISSUE TITLE
feat(config): Add env variables and some other templating stuff

### ISSUE THREAD

**Issue by jochumdev** [go-orb/go-orb#29]
This should be possible but only when the url of the config has "?template=true".

```yaml
  server:
    drpc:
      listen: unix://{{env.XDG_RUNTIME_DIR}}/opencloud/{{app.Name}}-drpc.sock
    grpc:
      listen: unix://{{env.XDG_RUNTIME_DIR}}/opencloud/{{app.Name}}-grpc.sock
```

Maybe a map[string]any works with text.Template, that would be very nice. If it works add that as parameter.
